// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//
// ================================================================================
//#MARKER REMOVE
recipes.remove(<computronics:computronics.colorfulLamp>);
recipes.remove(<PeripheralsPlusPlus:speaker>);
recipes.remove(<PeripheralsPlusPlus:chatBox>);
recipes.remove(<minecraft:poisonous_potato>);
recipes.remove(<TwilightForest:tile.TFUncraftingTable>);
recipes.remove(<EnderIO:blockEnchanter>);
recipes.remove(<DraconicEvolution:dissEnchanter>);
recipes.remove(<DraconicEvolution:weatherController>);
recipes.remove(<RandomThings:playerinterface>);
recipes.remove(<RandomThings:ingredient>);
recipes.remove(<RandomThings:magneticForce>);
recipes.remove(<DraconicEvolution:wyvernSword>);
recipes.remove(<DraconicEvolution:wyvernShovel>);
recipes.remove(<DraconicEvolution:wyvernPickaxe>);
recipes.remove(<DraconicEvolution:wyvernBow>);
recipes.remove(<DraconicEvolution:draconicHoe>);
recipes.remove(<DraconicEvolution:draconicAxe>);
/*
recipes.remove(<MorePlanet:ultra_violet_solar_panel>);
recipes.remove(<GalacticraftCore:tile.solar:4>);
recipes.remove(<GalacticraftCore:tile.solar>);
recipes.remove(<enderioaddons:itemMachineParts:4>);
recipes.remove(<Mekanism:BasicBlock:6>);
recipes.remove(<EnderIO:blockExperienceObelisk>);
recipes.remove(<rftools:saturationPlusEModuleItem>);
recipes.remove(<Mekanism:CardboardBox>);
recipes.remove(<IC2:blockElectric:5>);
recipes.remove(<IC2:itemArmorAdvBatpack>);
recipes.remove(<IC2:obscurator>);
recipes.remove(<IC2:itemScanner>);
recipes.remove(<IC2:itemNightvisionGoggles>);
*/
recipes.remove(<DraconicEvolution:wyvernBoots>);
recipes.remove(<DraconicEvolution:wyvernLeggs>);
recipes.remove(<DraconicEvolution:wyvernChest>);
recipes.remove(<DraconicEvolution:wyvernHelm>);
recipes.remove(<MekanismGenerators:Generator:5>);
recipes.remove(<MekanismGenerators:Generator:6>);
recipes.remove(<rftools:environmentalControllerBlock>);
recipes.remove(<Mekanism:MachineBlock:4>);
recipes.remove(<ExtraUtilities:enderQuarry>);
recipes.remove(<ComputerCraftEdu:CC-TurtleJunior>);
recipes.remove(<RArm:ItemTuberousArmor.Boots>);
recipes.remove(<RArm:ItemTuberousArmor.Leggings>);
recipes.remove(<RArm:ItemTuberousArmor.Chestplate>);
recipes.remove(<RArm:ItemTuberousArmor.Helm>);
recipes.remove(<BiomesOPlenty:enderporter>);
recipes.remove(<TConstruct:diamondApple>);
recipes.remove(<DraconicEvolution:grinder:3>);
recipes.remove(<MineFactoryReloaded:portaspawner>);
recipes.remove(<OpenComputers:powerConverter>);
/*
recipes.remove(<IC2:itemBatChargeAdv>);
recipes.remove(<IC2:blockElectric:7>);
recipes.remove(<IC2:blockPersonal:2>);
recipes.remove(<IC2:blockGenerator>);
recipes.remove(<IC2:itemRecipePart:3>);
recipes.remove(<IC2:itemBatChargeRE>);
recipes.remove(<IC2:itemArmorBatpack>);
recipes.remove(<LogisticsPipes:item.itemModule:300>);
recipes.remove(<Railcraft:machine.gamma:7>);
recipes.remove(<IC2:itemRecipePart:2>);
recipes.remove(<IC2:blockKineticGenerator:2>);
recipes.remove(<Railcraft:machine.gamma:6>);
recipes.remove(<IC2:upgradeModule:2>);
recipes.remove(<IC2:blockElectric>);
recipes.remove(<AdvancedSolarPanel:asp_crafting_items:12>);
recipes.remove(<IC2:itemAdvBat:*>);
recipes.remove(<IC2:itemBatREDischarged>);
*/
recipes.remove(<AdvancedSolarPanel:asp_crafting_items:13>);
recipes.remove(<AdvancedSolarPanel:BlockAdvSolarPanel>);
recipes.remove(<HardcoreQuesting:quest_book>);
recipes.remove(<Botania:sextant>);
/*
recipes.remove(<Mekanism:PartTransmitter:3>);
recipes.remove(<Mekanism:PartTransmitter:2>);
recipes.remove(<Mekanism:PartTransmitter:1>);
recipes.remove(<Mekanism:PartTransmitter>);
recipes.remove(<ExtraUtilities:defoliageAxe>);
recipes.remove(<Mekanism:EnergyTablet:100>);
recipes.remove(<GalacticraftCore:item.battery:100>);
recipes.remove(<MorePlanet:sulfur_battery:*>);
recipes.remove(<MorePlanet:uranium_battery:*>);
*/
recipes.remove(<DraconicEvolution:draconicBoots>);
recipes.remove(<DraconicEvolution:draconicLeggs>);
recipes.remove(<DraconicEvolution:draconicChest>);
recipes.remove(<DraconicEvolution:draconicHelm>);
/*
recipes.remove(<GalacticraftMars:tile.walkwayWire>);
recipes.remove(<MorePlanet:purple_crystal_solar_module:3>);
recipes.remove(<MorePlanet:power_crystal_generator>);
recipes.remove(<MorePlanet:purple_crystal_solar_module:2>);
recipes.remove(<MorePlanet:ultra_violet_solar_panel>);
recipes.remove(<GalacticraftCore:tile.aluminumWire:1>);
recipes.remove(<GalacticraftCore:tile.aluminumWire>);
recipes.remove(<GalacticraftMars:tile.marsMachine:8>);
recipes.remove(<GalacticraftCore:tile.enclosed:15>);
recipes.remove(<GalacticraftCore:tile.enclosed:14>);
recipes.remove(<GalacticraftCore:item.basicItem:1>);
recipes.remove(<GalacticraftCore:item.basicItem>);
recipes.remove(<GalacticraftCore:tile.machine2:4>);
recipes.remove(<GalacticraftCore:tile.machine2>);
recipes.remove(<GalacticraftCore:tile.machine>);
recipes.remove(<GalacticraftCore:tile.solar:4>);
recipes.remove(<GalacticraftCore:tile.solar>);
*/
recipes.remove(<Mekanism:WalkieTalkie>);
recipes.remove(<JABBA:moverDiamond>);
recipes.remove(<EnderIO:itemConduitProbe>);
recipes.remove(<simplyjetpacks:components:22>);
recipes.remove(<EnderIO:blockPowerMonitor>);
recipes.remove(<LatBlocks:materials:4>);
recipes.remove(<Mekanism:BasicBlock2>);
recipes.remove(<tinker_io:SmartOutput>);
recipes.remove(<RouterReborn:router_lampblock>);
recipes.remove(<tinker_io:fuelInputMachine>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<PneumaticCraft:compressedIronGear>, [[null, <ore:ingotIronCompressed>, null], [<ore:ingotIronCompressed>, <ore:gearStone>, <ore:ingotIronCompressed>], [null, <ore:ingotIronCompressed>, null]]);
recipes.removeShaped(<IC2:blockHeatGenerator:3>, [[<IC2:itemCasing:4>, <contenttweaker:ic2_rebattery>, <IC2:itemCasing:4>], [<IC2:itemCasing:4>, <IC2:itemPartCircuit>, <IC2:itemCasing:4>], [<IC2:itemCasing:4>, <IC2:itemRecipePart:5>, <IC2:itemCasing:4>]]);
recipes.removeShaped(<minecraft:packed_ice> * 4, [[<ore:ice>, <ore:ice>], [<ore:ice>, <ore:ice>]]);
recipes.removeShaped(<tinker_io:SmartOutput>, [[<TConstruct:materials:2>, <TConstruct:materials:2>], [<TConstruct:materials:2>, <TConstruct:materials:2>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
//recipes.addShapeless(<AdvancedSolarPanel:asp_crafting_items:9>, [<minecraft:glowstone>, <ore:craftingMolecularTransformer>, <IC2:itemArmorEnergypack:1>.giveBack(<IC2:itemArmorEnergypack:27>)]);
recipes.addShapeless(<PeripheralsPlusPlus:chatBox>, [<PeripheralsPlusPlus:speaker>]);
recipes.addShapeless(<PeripheralsPlusPlus:speaker>, [<PeripheralsPlusPlus:chatBox>]);
recipes.addShapeless(<minecraft:spawn_egg:94>, [<minecraft:egg>, <ore:dyeBlack>]);
recipes.addShapeless(<Enchiridion2:book>, [<ore:dirt>, <ore:dirt>]);
/*
recipes.addShapeless(<Mekanism:PartTransmitter:1>, [<Mekanism:PartTransmitter>]);
recipes.addShapeless(<Mekanism:PartTransmitter:2>, [<Mekanism:PartTransmitter:1>]);
recipes.addShapeless(<Mekanism:PartTransmitter:3>, [<Mekanism:PartTransmitter:2>]);
recipes.addShapeless(<Mekanism:PartTransmitter>, [<Mekanism:PartTransmitter:3>]);
*/
recipes.addShapeless(<JABBA:upgradeCore:8> * 3, [<JABBA:upgradeCore:9>]);
recipes.addShapeless(<JABBA:upgradeCore:9>, [<JABBA:upgradeCore:8>, <JABBA:upgradeCore:8>, <JABBA:upgradeCore:8>]);
recipes.addShapeless(<LatBlocks:materials:4>, [<LatBlocks:hammer>, <ore:itemNetherStar>]);
recipes.addShapeless(<minecraft:quartz_block>, [<ore:slabQuartz>, <ore:slabQuartz>]);
recipes.addShapeless(<minecraft:nether_brick>, [<ore:slabNetherBrick>, <ore:slabNetherBrick>]);
recipes.addShapeless(<minecraft:stonebrick>, [<ore:slabStoneBricks>, <ore:slabStoneBricks>]);
recipes.addShapeless(<minecraft:brick_block>, [<ore:slabBricks>, <ore:slabBricks>]);
recipes.addShapeless(<minecraft:sandstone>, [<ore:slabSandstone>, <ore:slabSandstone>]);
recipes.addShapeless(<minecraft:cobblestone>, [<ore:slabCobblestone>, <ore:slabCobblestone>]);
recipes.addShapeless(<minecraft:stone>, [<ore:slabStone>, <ore:slabStone>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<computronics:computronics.colorfulLamp>, [[<ore:blockIron>, <minecraft:redstone_lamp>, <ore:blockIron>], [<minecraft:redstone_lamp>, <minecraft:glowstone>, <minecraft:redstone_lamp>], [<ore:blockIron>, <minecraft:redstone_lamp>, <ore:blockIron>]]);
recipes.addShaped(<LatBlocks:materials:2>, [[null, <ore:blockGlassColorless>, null], [<ore:blockGlassColorless>, <Botania:lens>, <ore:blockGlassColorless>], [null, <ore:blockGlassColorless>, null]]);
//recipes.addShaped(<Mekanism:EnergyCube:100>.withTag({tier: "Advanced"}), [[<ore:alloyAdvanced>, <contenttweaker:mek_energytablet>, <ore:alloyAdvanced>], [<Mekanism:CompressedRedstone>, <Mekanism:EnergyCube:100>.withTag({tier: "Basic"}), <Mekanism:CompressedRedstone>], [<ore:alloyAdvanced>, <contenttweaker:mek_energytablet>, <ore:alloyAdvanced>]]);
//recipes.addShaped(<Mekanism:EnergyCube:100>.withTag({tier: "Basic"}), [[<ore:blockRedstone>, <contenttweaker:mek_energytablet>, <ore:blockRedstone>], [<ore:itemCompressedCarbon>, <Mekanism:BasicBlock:8>, <ore:itemCompressedCarbon>], [<ore:blockRedstone>, <contenttweaker:mek_energytablet>, <ore:blockRedstone>]]);
recipes.addShaped(<LatBlocks:materials:3>, [[<ore:blockPaintable>, <ore:blockPaintable>, <ore:blockPaintable>], [<ore:blockPaintable>, <AWWayofTime:bloodMagicBaseItems>, <ore:blockPaintable>], [<ore:blockPaintable>, <ore:blockPaintable>, <ore:blockPaintable>]]);
recipes.addShaped(<LatBlocks:materials:8>, [[<ThaumicTinkerer:darkQuartzItem>, <ThaumicTinkerer:darkQuartzItem>, <ThaumicTinkerer:darkQuartzItem>], [<ThaumicTinkerer:darkQuartzItem>, <ore:gemGlowium>, <ThaumicTinkerer:darkQuartzItem>], [<ThaumicTinkerer:darkQuartzItem>, <ThaumicTinkerer:darkQuartzItem>, <ThaumicTinkerer:darkQuartzItem>]]);
recipes.addShaped(<LatBlocks:materials>, [[<ore:dustGlowstone>, <ore:dustGlowstone>, <ore:dustGlowstone>], [<ore:dustGlowstone>, <ore:crystalCertusQuartz>, <ore:dustGlowstone>], [<ore:dustGlowstone>, <ore:dustGlowstone>, <ore:dustGlowstone>]]);
recipes.addShaped(<RArm:ItemTuberousArmor.Chestplate>, [[<minecraft:baked_potato>, <harvestcraft:freshwaterItem>, <minecraft:baked_potato>], [<minecraft:baked_potato>, <minecraft:poisonous_potato>, <minecraft:baked_potato>], [<minecraft:baked_potato>, <minecraft:baked_potato>, <minecraft:baked_potato>]]);
recipes.addShaped(<RArm:ItemTuberousArmor.Boots>, [[<minecraft:baked_potato>, <harvestcraft:freshwaterItem>, <minecraft:baked_potato>], [<minecraft:baked_potato>, <minecraft:poisonous_potato>, <minecraft:baked_potato>]]);
recipes.addShaped(<RArm:ItemTuberousArmor.Leggings>, [[<minecraft:baked_potato>, <minecraft:poisonous_potato>, <minecraft:baked_potato>], [<minecraft:baked_potato>, <harvestcraft:freshwaterItem>, <minecraft:baked_potato>], [<minecraft:baked_potato>, null, <minecraft:baked_potato>]]);
recipes.addShaped(<RArm:ItemTuberousArmor.Helm>, [[<minecraft:baked_potato>, <minecraft:poisonous_potato>, <minecraft:baked_potato>], [<minecraft:baked_potato>, <harvestcraft:freshwaterItem>, <minecraft:baked_potato>]]);
recipes.addShaped(<DraconicEvolution:draconiumChest>, [[<DraconicEvolution:draconiumIngot>, <TConstruct:CraftingStation>, <DraconicEvolution:draconiumIngot>], [<IronChest:BlockIronChest:6>, <DraconicEvolution:wyvernCore>, <IronChest:BlockIronChest:6>], [<ore:ingotDraconium>, <ThermalExpansion:Machine>, <DraconicEvolution:draconiumIngot>]]);
recipes.addShaped(<EnderIO:blockEnchanter>, [[<minecraft:enchanted_book>, <minecraft:enchanting_table>, <minecraft:enchanted_book>], [<EnderIO:itemAlloy:6>, <EnderIO:itemAlloy:6>, <EnderIO:itemAlloy:6>], [null, <EnderIO:itemAlloy:6>, null]]);
recipes.addShaped(<DraconicEvolution:dissEnchanter>, [[<minecraft:ender_eye>, <contenttweaker:enchanced_nether_star>, <minecraft:ender_eye>], [<contenttweaker:emerald_plate>, <EnderIO:blockEnchanter>, <contenttweaker:emerald_plate>], [<DraconicEvolution:wyvernCore>, <contenttweaker:enchanced_nether_star>, <DraconicEvolution:wyvernCore>]]);
recipes.addShaped(<DraconicEvolution:weatherController>, [[<ore:rodBlaze>, <ore:ingotDraconium>, <ore:rodBlaze>], [<minecraft:tnt>, <DraconicEvolution:awakenedCore>, <minecraft:tnt>], [<ore:ingotDraconium>, <minecraft:enchanting_table>, <ore:ingotDraconium>]]);
recipes.addShaped(<RandomThings:playerinterface>, [[<Mekanism:BasicBlock:2>, <ore:transdimBlock>, <ore:blockRefinedObsidian>], [<contenttweaker:enchanced_nether_star>, <RandomThings:ingredient>, <contenttweaker:enchanced_nether_star>], [<Mekanism:BasicBlock:2>, <Translocator:translocator>, <Mekanism:BasicBlock:2>]]);
recipes.addShaped(<RandomThings:ingredient>, [[<BigReactors:BRMetalBlock:3>, <BigReactors:BRMetalBlock:3>, <BigReactors:BRMetalBlock:3>], [<BigReactors:BRMetalBlock:3>, <ore:gemGelid>, <BigReactors:BRMetalBlock:3>], [<BigReactors:BRMetalBlock:3>, <BigReactors:BRMetalBlock:3>, <BigReactors:BRMetalBlock:3>]]);
recipes.addShaped(<DraconicEvolution:wyvernBow>, [[null, <DraconicEvolution:wyvernCore>, null], [<ore:ingotDraconium>, <RedstoneArsenal:tool.bowFlux>, <ore:ingotDraconium>], [null, <DraconicEvolution:draconiumEnergyCore>, null]]);
recipes.addShaped(<DraconicEvolution:wyvernPickaxe>, [[null, <DraconicEvolution:wyvernCore>, null], [<ore:ingotDraconium>, <RArm:ItemPickaxeGelidEnderium>, <ore:ingotDraconium>], [null, <DraconicEvolution:draconiumEnergyCore>, null]]);
recipes.addShaped(<DraconicEvolution:wyvernShovel>, [[null, <DraconicEvolution:wyvernCore>, null], [<ore:ingotDraconium>, <RArm:ItemShovelGelidEnderium>, <ore:ingotDraconium>], [null, <DraconicEvolution:draconiumEnergyCore>, null]]);
recipes.addShaped(<DraconicEvolution:wyvernSword>, [[null, <DraconicEvolution:wyvernCore>, null], [<ore:ingotDraconium>, <RArm:ItemSwordGelidEnderium>, <ore:ingotDraconium>], [null, <DraconicEvolution:draconiumEnergyCore>, null]]);
recipes.addShaped(<DraconicEvolution:draconicHoe>, [[null, <DraconicEvolution:awakenedCore>, null], [<ore:ingotDraconiumAwakened>, <ExtraUtilities:temporalHoe>, <ore:ingotDraconiumAwakened>], [null, <DraconicEvolution:draconiumEnergyCore:1>, null]]);
recipes.addShaped(<DraconicEvolution:draconicAxe>, [[null, <DraconicEvolution:awakenedCore>, null], [<ore:ingotDraconiumAwakened>, <RArm:ItemAxeGelidEnderium>, <ore:ingotDraconiumAwakened>], [null, <DraconicEvolution:draconiumEnergyCore:1>, null]]);
recipes.addShaped(<contenttweaker:de_wyvern_armor_part> * 8, [[<DraconicEvolution:wyvernPickaxe>, <DraconicEvolution:wyvernHelm>, <IC2:itemCellEmpty:3>], [<DraconicEvolution:wyvernLeggs>, <DraconicEvolution:wyvernChest>, <IC2:itemCellEmpty:3>], [<DraconicEvolution:wyvernBoots>, <IC2:itemCellEmpty:3>, <IC2:itemCellEmpty:3>]]);
recipes.addShaped(<PeripheralsPlusPlus:chatBox>, [[<minecraft:noteblock>, <minecraft:gold_ingot>, <minecraft:noteblock>], [<ore:ingotGold>, <contenttweaker:trusted>, <minecraft:gold_ingot>], [<minecraft:noteblock>, <minecraft:gold_ingot>, <minecraft:noteblock>]]);
recipes.addShaped(<enderioaddons:itemMachineParts:4>, [[<ore:ingotDarkSteel>, <EnderIO:item.darkSteel_pickaxe>.withTag({ench: [{lvl: 5 as short, id: 32 as short}, {lvl: 3 as short, id: 34 as short}]}), <ore:ingotDarkSteel>], [<minecraft:lava_bucket>, <ore:itemMachineChassi>, <minecraft:water_bucket>], [<ore:itemEnderCrystal>, <EnderIO:itemFrankenSkull:2>, <ore:itemEnderCrystal>]]);
recipes.addShaped(<enderioaddons:itemMachineParts:4>, [[<ore:ingotDarkSteel>, <EnderIO:item.darkSteel_pickaxe>.withTag({ench: [{lvl: 5 as short, id: 32 as short}, {lvl: 3 as short, id: 34 as short}]}), <ore:ingotDarkSteel>], [<ore:listAllwater>, <ore:itemMachineChassi>, <minecraft:lava_bucket>], [<ore:itemEnderCrystal>, <EnderIO:itemFrankenSkull:2>, <ore:itemEnderCrystal>]]);
recipes.addShaped(<contenttweaker:manyullyn_pickaxe>, [[<TConstruct:materials:5>, <ore:ingotManyullyn>, <ore:ingotManyullyn>], [null, <ore:woodStick>, null], [null, <minecraft:stick>, null]]);
recipes.addShaped(<EnderIO:blockExperienceObelisk>, [[null, <EnderIO:itemXpTransfer>, null], [null, <contenttweaker:endless_dust>, null], [<ore:ingotSoularium>, <EnderIO:itemMachinePart>, <EnderIO:itemAlloy:7>]]);
recipes.addShaped(<rftools:saturationPlusEModuleItem>, [[<rftools:saturationEModuleItem>, <rftools:syringeItem>.withTag({mobName: "Zombie", level: 10})], [<ExtraUtilities:defoliageAxe>, null]]);
recipes.addShaped(<Mekanism:CardboardBox>, [[<ore:pulpWood>, <ore:pulpWood>, <ore:pulpWood>], [<ore:pulpWood>, <JABBA:moverDiamond>, <ore:pulpWood>], [<ore:pulpWood>, <ore:pulpWood>, <ore:pulpWood>]]);
recipes.addShaped(<contenttweaker:emerald_plate>, [[<minecraft:emerald>, <minecraft:emerald_block>, <ore:gemEmerald>], [<ore:ingotUnstable>, <ore:ingotUnstable>, <ore:ingotUnstable>], [<ore:gemEmerald>, <ore:blockEmerald>, <ore:gemEmerald>]]);
recipes.addShaped(<contenttweaker:chifung>, [[<minecraft:crafting_table>, <minecraft:crafting_table>, <ore:crafterWood>], [<ore:crafterWood>, <ore:crafterWood>, <ore:crafterWood>], [<minecraft:crafting_table>, <minecraft:crafting_table>, <ore:crafterWood>]]);
/*
recipes.addShaped(<IC2:blockElectric:5>, [[null, <IC2:itemCable:3>, null], [<ore:circuitBasic>, <IC2:blockElectric:4>, <contenttweaker:ic2_reAdvBat>], [null, <IC2:itemCable:3>, null]]);
recipes.addShaped(<IC2:obscurator:27>, [[<minecraft:redstone>, <contenttweaker:ic2_reAdvBat>, <minecraft:redstone>], [<IC2:itemCable:3>, <IC2:itemPartCircuitAdv>, <IC2:itemCable:3>], [<minecraft:redstone>, <ore:dustRedstone>, <minecraft:redstone>]]);
recipes.addShaped(<IC2:itemArmorAdvBatpack:27>, [[<contenttweaker:ic2_reAdvBat>, <ore:circuitBasic>, <contenttweaker:ic2_reAdvBat>], [<contenttweaker:ic2_reAdvBat>, <IC2:itemCasing>, <contenttweaker:ic2_reAdvBat>], [<contenttweaker:ic2_reAdvBat>, null, <contenttweaker:ic2_reAdvBat>]]);
recipes.addShaped(<IC2:itemNightvisionGoggles:27>, [[<IC2:reactorHeatSwitchDiamond:1>, <contenttweaker:ic2_reAdvBat>, <IC2:reactorHeatSwitchDiamond:1>], [<IC2:blockLuminatorDark>, <IC2:blockAlloyGlass>, <IC2:blockLuminatorDark>], [<IC2:itemRubber>, <IC2:itemPartCircuitAdv>, <IC2:itemRubber>]]);
recipes.addShaped(<IC2:itemScanner:26>, [[<IC2:itemCasing:3>, <ore:dustGlowstone>, <IC2:itemCasing:3>], [<ore:circuitBasic>, <contenttweaker:ic2_reAdvBat>, <ore:circuitBasic>], [<IC2:itemCable>, <IC2:itemCable>, <IC2:itemCable>]]);
*/
recipes.addShaped(<DraconicEvolution:wyvernChest>, [[<ore:ingotDraconium>, <DraconicEvolution:wyvernCore>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <IC2:itemArmorNanoChestplate:*>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <DraconicEvolution:draconiumEnergyCore>, <ore:ingotDraconium>]]);
recipes.addShaped(<DraconicEvolution:wyvernHelm>, [[<ore:ingotDraconium>, <DraconicEvolution:wyvernCore>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <IC2:itemArmorNanoHelmet:*>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <DraconicEvolution:draconiumEnergyCore>, <ore:ingotDraconium>]]);
recipes.addShaped(<DraconicEvolution:wyvernLeggs>, [[<ore:ingotDraconium>, <DraconicEvolution:wyvernCore>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <IC2:itemArmorNanoLegs:*>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <DraconicEvolution:draconiumEnergyCore>, <ore:ingotDraconium>]]);
recipes.addShaped(<DraconicEvolution:wyvernBoots>, [[<ore:ingotDraconium>, <DraconicEvolution:wyvernCore>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <IC2:itemArmorNanoBoots:*>, <ore:ingotDraconium>], [<ore:ingotDraconium>, <DraconicEvolution:draconiumEnergyCore>, <ore:ingotDraconium>]]);
/*
recipes.addShaped(<MekanismGenerators:Generator:6>, [[null, <Mekanism:Ingot:1>, null], [<Mekanism:Ingot:1>, <Mekanism:AtomicAlloy>, <Mekanism:Ingot:1>], [<contenttweaker:mek_energytablet>, <Mekanism:ControlCircuit:2>, <contenttweaker:mek_energytablet>]]);
recipes.addShaped(<MekanismGenerators:Generator:5>, [[<MekanismGenerators:Generator:1>, <ore:itemEnrichedAlloy>, <MekanismGenerators:Generator:1>], [<MekanismGenerators:Generator:1>, <ore:itemEnrichedAlloy>, <MekanismGenerators:Generator:1>], [<ore:ingotIron>, <Mekanism:ControlCircuit:1>, <ore:ingotIron>]]);
recipes.addShaped(<rftools:environmentalControllerBlock>, [[<contenttweaker:emerald_plate>, <rftools:infusedDiamondItem>, <contenttweaker:diamond_plate>], [<rftools:infusedDiamondItem>, <ThermalExpansion:Frame:3>, <rftools:infusedDiamondItem>], [<contenttweaker:diamond_plate>, <rftools:infusedDiamondItem>, <contenttweaker:emerald_plate>]]);
*/
recipes.addShaped(<Mekanism:MachineBlock:4>, [[<Mekanism:TeleportationCore>, <PneumaticCraft:pcbBlueprint>, <Mekanism:TeleportationCore>], [<Mekanism:MachineBlock:15>, <Mekanism:Robit:1>, <Mekanism:MachineBlock:15>], [<StevesCarts:ModuleComponents:47>, <ExtraUtilities:enderQuarry>, <StevesCarts:ModuleComponents:47>]]);
recipes.addShaped(<ExtraUtilities:enderQuarry>, [[<StevesCarts:ModuleComponents:22>, <ExtraUtilities:enderCollector>, <StevesCarts:ModuleComponents:22>], [<ore:blockEnderCore>, <ExtraUtilities:decorativeBlock1:12>, <ore:blockEnderCore>], [<ExtraUtilities:enderThermicPump>, <contenttweaker:manyullyn_pickaxe>, <ExtraUtilities:enderThermicPump>]]);
recipes.addShaped(<ComputerCraftEdu:CC-TurtleJunior>, [[<minecraft:wool>, <minecraft:wool>, <ore:blockWoolWhite>], [<ore:blockWoolWhite>, <ComputerCraft:CC-TurtleAdvanced>, <ore:blockWoolWhite>], [<minecraft:wool>, <minecraft:ender_chest>, <ore:blockWoolWhite>]]);
recipes.addShaped(<TConstruct:diamondApple>, [[<minecraft:diamond>, <minecraft:diamond>, <minecraft:diamond>], [<minecraft:diamond>, <ore:cropApple>, <minecraft:diamond>], [<ore:gemDiamond>, <ore:gemDiamond>, <minecraft:diamond>]]);
recipes.addShaped(<DraconicEvolution:grinder:3>, [[<ore:ingotSteel>, <ore:ingotDraconium>, <ore:ingotSteel>], [<ExtraUtilities:ethericsword>, <DraconicEvolution:wyvernCore>, <ExtraUtilities:ethericsword>], [<ore:ingotSteel>, <EnderIO:itemFrankenSkull:2>, <ore:ingotSteel>]]);
recipes.addShaped(<MineFactoryReloaded:portaspawner>, [[<ore:ingotGold>, <ore:ingotEnderium>, <ore:ingotGold>], [<ore:ingotEnderium>, <ore:itemNetherStar>, <ore:ingotEnderium>], [<ore:ingotGold>, <ore:ingotEnderium>, <ore:ingotGold>]]);
recipes.addShaped(<contenttweaker:diamond_plate>, [[<Railcraft:slab:8>, <Railcraft:slab:8>, <Railcraft:slab:8>], [<ore:ingotUnstable>, <ore:ingotUnstable>, <ore:ingotUnstable>], [<Railcraft:slab:8>, <Railcraft:slab:8>, <Railcraft:slab:8>]]);
/*
recipes.addShaped(<contenttweaker:ic2_rebattery>, [[null, <IC2:itemCable:13>, null], [<IC2:itemCasing:1>, <ore:dustRedstone>, <IC2:itemCasing:1>], [<IC2:itemCasing:1>, <ore:dustRedstone>, <IC2:itemCasing:1>]]);
recipes.addShaped(<contenttweaker:ic2_reAdvBat>, [[<IC2:itemCable>, <IC2:itemCasing:2>, <IC2:itemCable>], [<IC2:itemCasing:2>, <ore:dustSulfur>, <IC2:itemCasing:2>], [<IC2:itemCasing:2>, <ore:dustLead>, <IC2:itemCasing:2>]]);
recipes.addShaped(<IC2:itemBatChargeAdv>, [[<IC2:reactorHeatSwitch:1>, <contenttweaker:ic2_reAdvBat>, <IC2:reactorHeatSwitch:1>], [<contenttweaker:ic2_reAdvBat>, <IC2:itemBatChargeRE:26>, <contenttweaker:ic2_reAdvBat>], [<IC2:reactorHeatSwitch:1>, <contenttweaker:ic2_reAdvBat>, <IC2:reactorHeatSwitch:1>]]);
recipes.addShaped(<IC2:blockElectric:7>, [[<ore:plateBronze>, <IC2:itemCable>, <ore:plateBronze>], [<contenttweaker:ic2_reAdvBat>, <contenttweaker:ic2_reAdvBat>, <contenttweaker:ic2_reAdvBat>], [<ore:plateBronze>, <ore:plateBronze>, <ore:plateBronze>]]);
recipes.addShaped(<IC2:blockPersonal:2>, [[<ore:dustRedstone>, <contenttweaker:ic2_rebattery>, <ore:dustRedstone>], [<IC2:itemCable>, <IC2:blockMachine>, <IC2:itemCable>]]);
recipes.addShaped(<IC2:blockGenerator>, [[null, <contenttweaker:ic2_rebattery>, null], [<ore:plateIron>, <ore:plateIron>, <ore:plateIron>], [null, <IC2:blockMachine:1>, null]]);
recipes.addShaped(<IC2:itemRecipePart:3>, [[null, <IC2:itemCable:1>, <IC2:itemCasing:4>], [<contenttweaker:ic2_rebattery>, <ore:circuitBasic>, <IC2:itemRecipePart:1>], [null, <IC2:itemCable:1>, <IC2:itemCasing:4>]]);
recipes.addShaped(<IC2:itemBatChargeRE>, [[<ore:circuitBasic>, <contenttweaker:ic2_rebattery>, <ore:circuitBasic>], [<contenttweaker:ic2_rebattery>, null, <contenttweaker:ic2_rebattery>], [<ore:circuitBasic>, <contenttweaker:ic2_rebattery>, <ore:circuitBasic>]]);
recipes.addShaped(<IC2:itemArmorBatpack>, [[<contenttweaker:ic2_rebattery>, <ore:circuitBasic>, <contenttweaker:ic2_rebattery>], [<contenttweaker:ic2_rebattery>, <ore:plankWood>, <contenttweaker:ic2_rebattery>], [<contenttweaker:ic2_rebattery>, null, <contenttweaker:ic2_rebattery>]]);
recipes.addShaped(<LogisticsPipes:item.itemModule:300>, [[<ore:circuitBasic>, <ore:gearGold>, <contenttweaker:ic2_rebattery>], [<ore:dustRedstone>, <LogisticsPipes:item.itemModule>, <ore:dustRedstone>], [<contenttweaker:ic2_rebattery>, <ore:dustRedstone>, <ore:circuitBasic>]]);
recipes.addShaped(<Railcraft:machine.gamma:7>, [[<contenttweaker:ic2_rebattery>, <Railcraft:detector:10>, <contenttweaker:ic2_rebattery>], [<contenttweaker:ic2_rebattery>, <IC2:blockMachine>, <contenttweaker:ic2_rebattery>], [<contenttweaker:ic2_rebattery>, <ore:blockHopper>, <contenttweaker:ic2_rebattery>]]);
recipes.addShaped(<IC2:itemRecipePart:2>, [[<contenttweaker:ic2_rebattery>, <IC2:itemCable:1>, <IC2:itemCasing:4>], [<contenttweaker:ic2_rebattery>, <ore:circuitBasic>, <IC2:itemRecipePart:1>], [<contenttweaker:ic2_rebattery>, <IC2:itemCable:1>, <IC2:itemCasing:4>]]);
recipes.addShaped(<IC2:blockKineticGenerator:2>, [[<IC2:itemCasing:4>, <contenttweaker:ic2_rebattery>, <IC2:itemCasing:4>], [<IC2:itemCasing:4>, <IC2:itemRecipePart:11>, <IC2:itemCasing:4>], [<IC2:itemCasing:4>, <IC2:itemRecipePart:1>, <IC2:itemCasing:4>]]);
recipes.addShaped(<Railcraft:machine.gamma:6>, [[<contenttweaker:ic2_rebattery>, <ore:blockHopper>, <contenttweaker:ic2_rebattery>], [<contenttweaker:ic2_rebattery>, <IC2:blockMachine>, <contenttweaker:ic2_rebattery>], [<contenttweaker:ic2_rebattery>, <Railcraft:detector:10>, <contenttweaker:ic2_rebattery>]]);
recipes.addShaped(<IC2:upgradeModule:2>, [[<ore:plankWood>, <ore:plankWood>, <ore:plankWood>], [<IC2:itemCable>, <contenttweaker:ic2_rebattery>, <IC2:itemCable>], [<ore:plankWood>, <ore:circuitBasic>, <ore:plankWood>]]);
recipes.addShaped(<IC2:blockHeatGenerator:3>, [[<IC2:itemCasing:4>, <contenttweaker:ic2_rebattery>, <IC2:itemCasing:4>], [<IC2:itemCasing:4>, <IC2:itemPartCircuit>, <IC2:itemCasing:4>], [<IC2:itemCasing:4>, <IC2:itemRecipePart:5>, <IC2:itemCasing:4>]]);
recipes.addShaped(<IC2:blockElectric>, [[<ore:plankWood>, <IC2:itemCable:13>, <ore:plankWood>], [<contenttweaker:ic2_rebattery>, <contenttweaker:ic2_rebattery>, <contenttweaker:ic2_rebattery>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
*/
recipes.addShaped(<AdvancedSolarPanel:asp_crafting_items:12>, [[<AdvancedSolarPanel:asp_crafting_items:5>, <IC2:reactorReflectorThick:1>, <AdvancedSolarPanel:asp_crafting_items:5>], [<AdvancedSolarPanel:asp_crafting_items:5>, null, <AdvancedSolarPanel:asp_crafting_items:5>], [<AdvancedSolarPanel:asp_crafting_items:5>, <IC2:reactorReflectorThick:1>, <AdvancedSolarPanel:asp_crafting_items:5>]]);
recipes.addShaped(<AdvancedSolarPanel:asp_crafting_items:13>, [[<AdvancedSolarPanel:asp_crafting_items:4>, <ore:blockNetherStar>, <AdvancedSolarPanel:asp_crafting_items:4>], [<ore:blockNetherStar>, <ore:pearlEnderEye>, <ore:blockNetherStar>], [<AdvancedSolarPanel:asp_crafting_items:4>, <ore:blockNetherStar>, <AdvancedSolarPanel:asp_crafting_items:4>]]);
recipes.addShaped(<AdvancedSolarPanel:BlockAdvSolarPanel>, [[<AdvancedSolarPanel:asp_crafting_items:5>, <AdvancedSolarPanel:asp_crafting_items:5>, <AdvancedSolarPanel:asp_crafting_items:5>], [<IC2:itemPartAlloy>, <CompactSolars:CompactSolarBlock:2>, <IC2:itemPartAlloy>], [<ore:circuitAdvanced>, <AdvancedSolarPanel:asp_crafting_items:8>, <ore:circuitAdvanced>]]);
/*
recipes.addShaped(<contenttweaker:mek_energytablet>, [[<ore:dustRedstone>, <ore:ingotGold>, <ore:dustRedstone>], [<ore:itemEnrichedAlloy>, <minecraft:gold_ingot>, <ore:itemEnrichedAlloy>], [<ore:dustRedstone>, <ore:ingotGold>, <ore:dustRedstone>]]);
recipes.addShaped(<contenttweaker:gcc_battery>, [[null, <ore:compressedTin>, null], [<ore:compressedTin>, <minecraft:redstone>, <ore:compressedTin>], [<ore:compressedTin>, <ore:itemCoal>, <ore:compressedTin>]]);
*/
recipes.addShaped(<DraconicEvolution:draconicBoots>, [[<ore:ingotDraconiumAwakened>, <DraconicEvolution:awakenedCore>, <ore:ingotDraconiumAwakened>], [<contenttweaker:de_wyvern_armor_part>, <IC2:itemArmorQuantumBoots:26>, <contenttweaker:de_wyvern_armor_part>], [<ore:ingotDraconiumAwakened>, <DraconicEvolution:draconiumEnergyCore:1>, <ore:ingotDraconiumAwakened>]]);
recipes.addShaped(<DraconicEvolution:draconicLeggs>, [[<ore:ingotDraconiumAwakened>, <DraconicEvolution:awakenedCore>, <ore:ingotDraconiumAwakened>], [<contenttweaker:de_wyvern_armor_part>, <IC2:itemArmorQuantumLegs:26>, <contenttweaker:de_wyvern_armor_part>], [<ore:ingotDraconiumAwakened>, <DraconicEvolution:draconiumEnergyCore:1>, <ore:ingotDraconiumAwakened>]]);
recipes.addShaped(<DraconicEvolution:draconicChest>, [[<ore:ingotDraconiumAwakened>, <DraconicEvolution:awakenedCore>, <ore:ingotDraconiumAwakened>], [<contenttweaker:de_wyvern_armor_part>, <GraviSuite:graviChestPlate>, <contenttweaker:de_wyvern_armor_part>], [<ore:ingotDraconiumAwakened>, <DraconicEvolution:draconiumEnergyCore:1>, <ore:ingotDraconiumAwakened>]]);
recipes.addShaped(<DraconicEvolution:draconicHelm>, [[<ore:ingotDraconiumAwakened>, <DraconicEvolution:awakenedCore>, <ore:ingotDraconiumAwakened>], [<contenttweaker:de_wyvern_armor_part>, <IC2:itemArmorQuantumHelmet:26>, <contenttweaker:de_wyvern_armor_part>], [<ore:ingotDraconiumAwakened>, <DraconicEvolution:draconiumEnergyCore:1>, <ore:ingotDraconiumAwakened>]]);
/*
recipes.addShaped(<GalacticraftMars:tile.walkwayWire>, [[<ore:compressedTitanium>, <ore:compressedTitanium>, <ore:compressedTitanium>], [<ThermalDynamics:ThermalDynamics_0:2>, <ore:compressedTitanium>, <ThermalDynamics:ThermalDynamics_0:2>], [<ThermalDynamics:ThermalDynamics_0:2>, <ThermalDynamics:ThermalDynamics_0:2>, <ThermalDynamics:ThermalDynamics_0:2>]]);
recipes.addShaped(<MorePlanet:purple_crystal_solar_module:3>, [[<MorePlanet:purple_crystal_solar_module:2>, <MorePlanet:purple_crystal_solar_module:2>, <MorePlanet:purple_crystal_solar_module:2>], [<ThermalDynamics:ThermalDynamics_0:2>, <ThermalDynamics:ThermalDynamics_0:2>, <ThermalDynamics:ThermalDynamics_0:2>], [<MorePlanet:purple_crystal_solar_module:2>, <MorePlanet:purple_crystal_solar_module:2>, <MorePlanet:purple_crystal_solar_module:2>]]);
recipes.addShaped(<MorePlanet:power_crystal_generator>, [[<ore:compressedTitanium>, <ore:compressedTitanium>, <ore:compressedTitanium>], [<GalacticraftMars:item.itemBasicAsteroids>, <minecraft:furnace>, <GalacticraftMars:item.itemBasicAsteroids>], [<GalacticraftMars:item.itemBasicAsteroids>, <ThermalDynamics:ThermalDynamics_0:2>, <GalacticraftMars:item.itemBasicAsteroids>]]);
recipes.addShaped(<MorePlanet:purple_crystal_solar_module:2> * 2 , [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<MorePlanet:purple_crystal_solar_module:1>, <MorePlanet:purple_crystal_solar_module:1>, <MorePlanet:purple_crystal_solar_module:1>], [<ThermalDynamics:ThermalDynamics_0:2>, <ThermalDynamics:ThermalDynamics_0:2>, <ThermalDynamics:ThermalDynamics_0:2>]]);
recipes.addShaped(<MorePlanet:ultra_violet_solar_panel>, [[<GalacticraftMars:item.itemBasicAsteroids>, <MorePlanet:purple_crystal_solar_module:3>, <GalacticraftMars:item.itemBasicAsteroids>], [<GalacticraftMars:item.itemBasicAsteroids>, <GalacticraftCore:item.steelPole>, <GalacticraftMars:item.itemBasicAsteroids>], [<ThermalDynamics:ThermalDynamics_0:2>, <MorePlanet:purple_crystal_solar_module>, <ThermalDynamics:ThermalDynamics_0:2>]]);
recipes.addShaped(<GalacticraftMars:tile.marsMachine:8>, [[<ore:ingotDesh>, <GalacticraftCore:item.basicItem:19>, <ore:ingotDesh>], [<ore:compressedDesh>, <ore:waferAdvanced>, <ore:compressedDesh>], [<ore:ingotDesh>, <ThermalDynamics:ThermalDynamics_0:1>, <ore:ingotDesh>]]);
recipes.addShaped(<GalacticraftCore:item.basicItem:1>, [[<GalacticraftCore:item.basicItem>, <GalacticraftCore:item.basicItem>, <GalacticraftCore:item.basicItem>], [<ThermalDynamics:ThermalDynamics_0:1>, <ThermalDynamics:ThermalDynamics_0:1>, <ThermalDynamics:ThermalDynamics_0:1>], [<GalacticraftCore:item.basicItem>, <GalacticraftCore:item.basicItem>, <GalacticraftCore:item.basicItem>]]);
recipes.addShaped(<GalacticraftCore:item.basicItem> * 2 , [[<ore:blockGlassColorless>, <ore:blockGlassColorless>, <ore:blockGlassColorless>], [<ore:waferSolar>, <ore:waferSolar>, <ore:waferSolar>], [<ThermalDynamics:ThermalDynamics_0:1>, <ThermalDynamics:ThermalDynamics_0:1>, <ThermalDynamics:ThermalDynamics_0:1>]]);
recipes.addShaped(<GalacticraftCore:tile.machine2:4>, [[<ore:ingotAluminum>, <minecraft:lever>, <ore:ingotAluminum>], [<minecraft:stone_button>, <minecraft:furnace>, <minecraft:stone_button>], [<ThermalDynamics:ThermalDynamics_0:1>, <minecraft:redstone_torch>, <ThermalDynamics:ThermalDynamics_0:1>]]);
recipes.addShaped(<GalacticraftCore:tile.machine2>, [[<ore:compressedSteel>, <minecraft:anvil>, <ore:compressedSteel>], [<ore:compressedSteel>, <ore:compressedBronze>, <ore:compressedSteel>], [<ThermalDynamics:ThermalDynamics_0:1>, <ore:waferAdvanced>, <ThermalDynamics:ThermalDynamics_0:1>]]);
recipes.addShaped(<GalacticraftCore:tile.solar:4>, [[<ore:compressedSteel>, <GalacticraftCore:item.basicItem:1>, <ore:compressedSteel>], [<ore:compressedSteel>, <GalacticraftCore:item.steelPole>, <ore:compressedSteel>], [<ThermalDynamics:ThermalDynamics_0:2>, <ore:waferAdvanced>, <ThermalDynamics:ThermalDynamics_0:2>]]);
recipes.addShaped(<GalacticraftCore:tile.solar>, [[<ore:compressedSteel>, <GalacticraftCore:item.basicItem:1>, <ore:compressedSteel>], [<ore:compressedSteel>, <GalacticraftCore:item.steelPole>, <ore:compressedSteel>], [<ThermalDynamics:ThermalDynamics_0:1>, <ore:waferBasic>, <ThermalDynamics:ThermalDynamics_0:1>]]);
*/
recipes.addShaped(<JABBA:moverDiamond>, [[null, <JABBA:mover>, null], [<contenttweaker:diamond_plate>, <contenttweaker:diamond_plate>, <contenttweaker:diamond_plate>]]);
recipes.addShaped(<EnderIO:itemConduitProbe>, [[<ore:ingotElectricalSteel>, <ThermalDynamics:ThermalDynamics_0>, <ore:ingotElectricalSteel>], [<ore:paneGlassColorless>, <minecraft:comparator>, <minecraft:glass_pane>], [<ore:itemSilicon>, <EnderIO:itemRedstoneConduit:2>, <EnderIO:itemMaterial>]]);
recipes.addShaped(<simplyjetpacks:components:22>, [[<ore:ingotElectricalSteel>, <EnderIO:itemBasicCapacitor>, <ore:ingotElectricalSteel>], [<ThermalDynamics:ThermalDynamics_0>, <EnderIO:itemBasicCapacitor>, <ThermalDynamics:ThermalDynamics_0>], [<EnderIO:itemMachinePart>, <ore:dustRedstone>, <EnderIO:itemMachinePart>]]);
recipes.addShaped(<EnderIO:blockPowerMonitor>, [[<EnderIO:itemAlloy>, <EnderIO:itemConduitProbe>, <EnderIO:itemAlloy>], [<EnderIO:itemAlloy>, <EnderIO:itemMachinePart>, <EnderIO:itemAlloy>], [<EnderIO:itemAlloy>, <ThermalDynamics:ThermalDynamics_0>, <EnderIO:itemAlloy>]]);
recipes.addShaped(<contenttweaker:universalcableultimate_horizontal_part>, [[<ore:ingotUnstable>, <ore:ingotUnstable>, <ore:ingotUnstable>], [<ImmersiveEngineering:metalDevice:6>, <EnderIO:itemPowerConduit:2>, <ImmersiveEngineering:metalDevice:6>], [<ore:ingotUnstable>, <ore:ingotUnstable>, <ore:ingotUnstable>]]);
recipes.addShaped(<contenttweaker:universalcableultimate_vertical_part>, [[<DraconicEvolution:draconicIngot>, <DraconicEvolution:energyCrystal:5>, <DraconicEvolution:draconicIngot>], [<ore:ingotDraconiumAwakened>, <ThermalDynamics:ThermalDynamics_0:6>, <ore:ingotDraconiumAwakened>], [<DraconicEvolution:draconicIngot>, <DraconicEvolution:energyCrystal:5>, <DraconicEvolution:draconicIngot>]]);
recipes.addShaped(<contenttweaker:universalcableultimate_core>, [[<ExtraUtilities:extractor_base:13>, <ore:chipsetEmerald>, <ExtraUtilities:extractor_base:13>], [<ore:chipsetEmerald>, <appliedenergistics2:item.ItemMultiMaterial:47>, <ore:chipsetEmerald>], [<ExtraUtilities:extractor_base:13>, <ore:chipsetEmerald>, <ExtraUtilities:extractor_base:13>]]);
//recipes.addShaped(<Mekanism:PartTransmitter:3> * 32 , [[<Mekanism:ControlCircuit:3>, <contenttweaker:universalcableultimate_horizontal_part>, <ore:alloyUltimate>], [<contenttweaker:universalcableultimate_vertical_part>, <contenttweaker:universalcableultimate_core>, <contenttweaker:universalcableultimate_vertical_part>], [<ore:alloyUltimate>, <contenttweaker:universalcableultimate_horizontal_part>, <Mekanism:ControlCircuit:3>]]);
recipes.addShaped(<Mekanism:BasicBlock2> * 2, [[<ore:ingotCopper>, <Forestry:ingotCopper>, <Forestry:ingotCopper>], [<IC2:itemPartAlloy>, <Mekanism:BasicBlock:9>, <IC2:itemPartAlloy>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);
recipes.addShaped(<tinker_io:SmartOutput>, [[<TConstruct:materials:2>, <ore:blockPackedIce>, <TConstruct:materials:2>], [<ore:blockPackedIce>, <ThermalDynamics:ThermalDynamics_32>, <ore:blockPackedIce>], [<TConstruct:materials:2>, <ore:blockPackedIce>, <TConstruct:materials:2>]]);
recipes.addShaped(<tinker_io:fuelInputMachine>, [[<TConstruct:materials:2>, <TConstruct:materials:2>, <TConstruct:materials:2>], [<TConstruct:materials:2>, <PneumaticCraft:omnidirectionalHopper>, <TConstruct:materials:2>], [<TConstruct:materials:2>, <TConstruct:materials:2>, <TConstruct:materials:2>]]);
