// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<AWWayofTime:emptySocket>);
recipes.remove(<Botania:manaMirror:1000>);
recipes.remove(<ThermalFoundation:bucket:5>);
recipes.remove(<StorageDrawers:controller>);
recipes.remove(<rftools:syringeItem>);
recipes.remove(<ExtraUtilities:generator:5>);
recipes.remove(<ExtraUtilities:generator:11>);
recipes.remove(<MineFactoryReloaded:machine.2>);
recipes.remove(<gendustry:PowerModule>);
recipes.remove(<rftools:environmentalControllerBlock>);
recipes.remove(<appliedenergistics2:tile.BlockInscriber>);
recipes.remove(<appliedenergistics2:tile.BlockCharger>);
recipes.remove(<RandomThings:playerinterface>);
recipes.remove(<ae2wct:wirelessCraftingTerminal>);
recipes.remove(<MineFactoryReloaded:plastic.sheet>);
recipes.remove(<DraconicEvolution:draconicCore>);
recipes.remove(<TConstruct:blankPattern>);
recipes.remove(<Mekanism:PartTransmitter:8>);
recipes.remove(<Mekanism:PartTransmitter:4>);
recipes.remove(<Mekanism:PartTransmitter:12>);
recipes.remove(<rftools:dimletResearcherBlock>);
recipes.remove(<ExtraUtilities:defoliageAxe>);
recipes.remove(<quantumflux:battlesuit_boots:1>);
recipes.remove(<quantumflux:battlesuit_leggings:1>);
recipes.remove(<quantumflux:battlesuit_helmet:1>);
recipes.remove(<quantumflux:battlesuit_plate>);
recipes.remove(<quantumflux:battlesuit_chestplate:1>);
recipes.remove(<Mekanism:ControlCircuit:2>);
recipes.remove(<Mekanism:ControlCircuit:1>);
recipes.remove(<ExtraUtilities:extractor_base>);
recipes.remove(<ExtraUtilities:extractor_base:6>);
recipes.remove(<ExtraUtilities:extractor_base:6>);
recipes.remove(<ExtraUtilities:extractor_base>);
recipes.remove(<ExtraUtilities:decorativeBlock1:11>);
recipes.remove(<ExtraUtilities:endConstructor>);
recipes.remove(<ExtraUtilities:endConstructor:2>);
recipes.remove(<ExtraUtilities:decorativeBlock1:1>);
recipes.remove(<ExtraUtilities:angelRing:*>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<ExtraUtilities:cobblestone_compressed>, [[<ore:cobblestone>, <minecraft:cobblestone>, <ore:cobblestone>], [<ore:cobblestone>, <minecraft:cobblestone>, <ore:cobblestone>], [<minecraft:cobblestone>, <ore:cobblestone>, <minecraft:cobblestone>]]);
recipes.removeShaped(<LogisticsPipes:logisticsSolidBlock:2>, [[<ore:ingotIron>, <ore:gearDiamond>, <ore:ingotIron>], [<ore:dustRedstone>, <LogisticsPipes:item.PipeItemsBasicLogistics>, <ore:dustRedstone>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);
recipes.removeShaped(<ExtraUtilities:golden_bag>, [[<ore:blockWool>, <ore:gemDiamond>, <ore:blockWool>], [<ore:ingotGold>, <ore:chestWood>, <ore:ingotGold>], [<ore:blockWool>, <minecraft:gold_block>, <ore:blockWool>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<Mystcraft:page>.withTag({symbol: "ModMat_tile.myst.crystal"}), [<ore:blockCrystalMatrix>, <Mystcraft:page>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<AWWayofTime:emptySocket>, [[<AWWayofTime:weakBloodShard>, <Thaumcraft:blockCosmeticOpaque:2>, <AWWayofTime:weakBloodShard>], [<Thaumcraft:blockCosmeticOpaque:2>, <ore:manaDiamond>, <Thaumcraft:blockCosmeticOpaque:2>], [<AWWayofTime:weakBloodShard>, <Thaumcraft:blockCosmeticOpaque:2>, <AWWayofTime:weakBloodShard>]]);
recipes.addShaped(<Avaritia:Neutronium_Compressor>, [[<ExtraUtilities:cobblestone_compressed:11>, <ExtraUtilities:cobblestone_compressed:15>, <ore:compressedDirt4x>], [<ExtraUtilities:cobblestone_compressed:13>, <Avaritia:Dire_Crafting>, <ExtraUtilities:cobblestone_compressed:13>], [<ore:compressedDirt4x>, <ExtraUtilities:cobblestone_compressed:15>, <ore:compressedDirt4x>]]);
recipes.addShaped(<Botania:manaMirror:1000>, [[null, <ore:manaPearl>, <ore:livingrock>], [null, <ore:livingwoodTwig>, <ore:gaiaIngot>], [<Botania:manaRingGreater:1000>, null, null]]);
recipes.addShaped(<ThermalFoundation:bucket:5>, [[<ore:bucketPetrotheum>, <ore:bucketRedstone>, <ore:bucketEnder>], [<ore:bucketGlowstone>, <ore:bucketPyrotheum>, <thaumicbases:pyroBucket>], [<ore:bucketAerotheum>, <ore:bucketCryotheum>, <PneumaticCraft:etchacidBucket>]]);
recipes.addShaped(<StorageDrawers:controller>, [[<ore:stone>, <ore:stone>, <ore:stone>], [<minecraft:comparator>, <StorageDrawers:compDrawers>, <minecraft:comparator>], [<ore:stone>, <JABBA:upgradeCore:8>, <ore:stone>]]);
recipes.addShaped(<contenttweaker:heet_ingot>, [[<IC2:itemRTGPellet>, <ExtraUtilities:block_bedrockium>, <IC2:itemRTGPellet>], [<ore:blockLudicrite>, <ThermalFoundation:bucket:5>, <ore:blockLudicrite>], [<IC2:itemRTGPellet>, <ExtraUtilities:block_bedrockium>, <IC2:itemRTGPellet>]]);
recipes.addShaped(<rftools:syringeItem>, [[<ore:ingotRefinedObsidian>, null, null], [null, <ore:ingotRefinedObsidian>, null], [null, null, <ore:bEnderAirBottle>]]);
recipes.addShaped(<GalacticraftCore:tile.machine2:4>, [[<ore:ingotAluminum>, <minecraft:lever>, <ImmersiveEngineering:metal:1>], [<minecraft:stone_button>, null, <minecraft:stone_button>], [<EnderIO:itemPowerConduit:2>, <BuildCraft|Silicon:laserBlock>, <EnderIO:itemPowerConduit:2>]]);
recipes.addShaped(<ExtraUtilities:generator:5>, [[<harvestcraft:frenchtoastItem>, <harvestcraft:frenchtoastItem>, <ore:foodFrenchtoast>], [<harvestcraft:frenchtoastItem>, <ExtraUtilities:generator>, <ore:foodFrenchtoast>], [<ore:blockRedstone>, <IC2:blockMachine:1>, <ore:blockRedstone>]]);
recipes.addShaped(<ExtraUtilities:generator:11>, [[<minecraft:nether_star>, <ore:blockLudicrite>, <minecraft:nether_star>], [<minecraft:nether_star>, <ore:blockUnstable>, <minecraft:nether_star>], [<ore:blockRedstone>, <IC2:blockMachine:1>, <ore:blockRedstone>]]);
recipes.addShaped(<ExtraUtilities:block_bedrockium>, [[<ore:compressedCobblestone8x>, <ExtraUtilities:cobblestone_compressed:6>, <ore:compressedCobblestone8x>], [<ExtraUtilities:cobblestone_compressed:6>, <ThermalFoundation:bucket:5>, <ExtraUtilities:cobblestone_compressed:6>], [<ore:compressedCobblestone8x>, <ExtraUtilities:cobblestone_compressed:6>, <ore:compressedCobblestone8x>]]);
recipes.addShaped(<MineFactoryReloaded:machine.2>, [[<ore:sheetPlastic>, <ThermalExpansion:Light>, <ore:sheetPlastic>], [<EnderIO:itemPowerConduit:2>, <BuildCraft|Builders:machineBlock>, <EnderIO:itemPowerConduit:2>], [<ore:blockGlassHardenedIlluminated>, <Mekanism:MachineBlock2:13>, <ore:blockGlassHardenedIlluminated>]]);
recipes.addShaped(<mo:machine_casing>, [[null, <mo:tritanium_plate>, null], [<ore:ingotTritanium>, null, <ore:ingotTritanium>], [<ore:ingotGold>, <DraconicEvolution:draconicCore>, <ore:ingotGold>]]);
recipes.addShaped(<DraconicEvolution:wyvernCore>, [[<ore:itemEnrichedAlloy>, <DraconicEvolution:draconicCore>, <ore:itemEnrichedAlloy>], [<DraconicEvolution:draconicCore>, null, <DraconicEvolution:draconicCore>], [<ore:itemEnrichedAlloy>, <DraconicEvolution:draconicCore>, <ore:itemEnrichedAlloy>]]);
recipes.addShaped(<gendustry:PowerModule>, [[<ore:gearBronze>, <ore:ingotGold>, <ore:gearBronze>], [<ore:craftingPiston>, <DraconicEvolution:wyvernCore>, <ore:craftingPiston>], [<ore:gearBronze>, <ore:ingotGold>, <ore:gearBronze>]]);
recipes.addShaped(<rftools:environmentalControllerBlock>, [[<ore:redstoneCrystal>, <ore:blockLudicrite>, <ore:redstoneCrystal>], [<Botania:storage:1>, <rftools:machineFrame>, <ore:blockThauminite>], [<ore:redstoneCrystal>, <ore:blockMithril>, <ore:redstoneCrystal>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInscriber>, [[<appliedenergistics2:tile.BlockSkyStone:1>, <minecraft:sticky_piston>, <appliedenergistics2:tile.BlockSkyStone:1>], [<ore:crystalPureFluix>, null, <LogisticsPipes:item.PipeItemsBasicLogistics>], [<appliedenergistics2:tile.BlockSkyStone:1>, <minecraft:sticky_piston>, <appliedenergistics2:tile.BlockSkyStone:1>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockInscriber>, [[<appliedenergistics2:tile.BlockSkyStone:1>, <minecraft:sticky_piston>, <appliedenergistics2:tile.BlockSkyStone:1>], [<ore:crystalFluix>, null, <LogisticsPipes:item.PipeItemsBasicLogistics>], [<appliedenergistics2:tile.BlockSkyStone:1>, <minecraft:sticky_piston>, <appliedenergistics2:tile.BlockSkyStone:1>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockCharger>, [[<appliedenergistics2:tile.BlockSkyStone:1>, <ore:crystalPureFluix>, <appliedenergistics2:tile.BlockSkyStone:1>], [<LogisticsPipes:item.PipeItemsBasicLogistics>, null, null], [<appliedenergistics2:tile.BlockSkyStone:1>, <ore:crystalPureFluix>, <appliedenergistics2:tile.BlockSkyStone:1>]]);
recipes.addShaped(<appliedenergistics2:tile.BlockCharger>, [[<appliedenergistics2:tile.BlockSkyStone:1>, <ore:crystalFluix>, <appliedenergistics2:tile.BlockSkyStone:1>], [<LogisticsPipes:item.PipeItemsBasicLogistics>, null, null], [<appliedenergistics2:tile.BlockSkyStone:1>, <ore:crystalFluix>, <appliedenergistics2:tile.BlockSkyStone:1>]]);
recipes.addShaped(<RandomThings:playerinterface>, [[<ore:blockRefinedObsidian>, <contenttweaker:enchanced_nether_star>, <ore:blockRefinedObsidian>], [<RandomThings:ingredient>, <PneumaticCraft:aerialInterface>, <RandomThings:ingredient>], [<ore:blockRefinedObsidian>, <contenttweaker:enchanced_nether_star>, <ore:blockRefinedObsidian>]]);
recipes.addShaped(<ae2wct:wirelessCraftingTerminal>, [[<appliedenergistics2:item.ItemMultiMaterial:47>, <appliedenergistics2:tile.BlockWireless>, <appliedenergistics2:item.ItemMultiMaterial:47>], [<extracells:storage.component:3>, <appliedenergistics2:item.ToolWirelessTerminal>, <extracells:storage.component:3>], [<extracells:storage.component:3>, <appliedenergistics2:tile.BlockDenseEnergyCell>, <extracells:storage.component:3>]]);
recipes.addShaped(<MineFactoryReloaded:plastic.sheet> * 4, [[<MineFactoryReloaded:plastic.raw>, <MineFactoryReloaded:plastic.raw>, <MineFactoryReloaded:plastic.raw>], [<MineFactoryReloaded:plastic.raw>, <MineFactoryReloaded:plastic.raw>, <MineFactoryReloaded:plastic.raw>], [<MineFactoryReloaded:plastic.raw>, <MineFactoryReloaded:plastic.raw>, <MineFactoryReloaded:plastic.raw>]]);
recipes.addShaped(<DraconicEvolution:draconicCore>, [[<ThermalFoundation:material:70>, <ore:ingotDraconium>, <ThermalFoundation:material:70>], [<ore:ingotDraconium>, <ore:manaDiamond>, <ore:ingotDraconium>], [<ThermalFoundation:material:70>, <ore:ingotDraconium>, <ThermalFoundation:material:70>]]);
recipes.addShaped(<TConstruct:blankPattern> * 2, [[<ore:plankWood>, <ore:stickWood>], [<ore:stickWood>, <ore:plankWood>]]);
recipes.addShaped(<EnderIO:itemGasConduit> * 8, [[<ore:itemConduitBinder>, <Mekanism:PartTransmitter:11>, <ore:itemConduitBinder>], [<Mekanism:PartTransmitter:11>, <ore:blockElectricalSteel>, <Mekanism:PartTransmitter:11>], [<ore:itemConduitBinder>, <Mekanism:PartTransmitter:11>, <ore:itemConduitBinder>]]);
recipes.addShaped(<Mekanism:PartTransmitter:8> * 8, [[<Mekanism:BasicBlock>, <ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>], [<ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>], [<ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>]]);
recipes.addShaped(<Mekanism:PartTransmitter:4> * 8, [[<Mekanism:BasicBlock:5>, <ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>], [<ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>], [<ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>, <ThermalDynamics:ThermalDynamics_16:2>]]);
recipes.addShaped(<Mekanism:PartTransmitter:12> * 8, [[<Mekanism:ControlCircuit>, <ThermalDynamics:ThermalDynamics_32>, <ThermalDynamics:ThermalDynamics_32>], [<ThermalDynamics:ThermalDynamics_32>, <ThermalDynamics:ThermalDynamics_32>, <ThermalDynamics:ThermalDynamics_32>], [<ThermalDynamics:ThermalDynamics_32>, <ThermalDynamics:ThermalDynamics_32>, <ThermalDynamics:ThermalDynamics_32>]]);
recipes.addShaped(<rftools:dimletResearcherBlock>, [[<ore:redstoneCrystal>, <Mystcraft:BlockBookReceptacle>, <ore:redstoneCrystal>], [<ore:chipsetComp>, <rftools:machineFrame>, <ore:chipsetComp>], [<EnderIO:blockIngotStorage:6>, <EnderIO:blockIngotStorage:6>, <ore:blockDarkSteel>]]);
recipes.addShaped(<Mystcraft:BlockCrystal> * 8, [[<ore:livingrock>, <ore:livingrock>, <ore:livingrock>], [<ore:livingrock>, <Mystcraft:page>.withTag({symbol: "ModMat_tile.myst.crystal"}), <ore:livingrock>], [<ore:livingrock>, <ore:livingrock>, <ore:livingrock>]]);
recipes.addShaped(<ImmersiveEngineering:material:15>, [[null, null, <ore:ingotSteel>], [null, <ore:ingotSteel>, null], [<ore:ingotSteel>, null, null]]);
recipes.addShaped(<quantumflux:battlesuit_leggings:1>, [[<quantumflux:upgradeToken>, <quantumflux:battlesuit_leggings>], [<RArm:ItemEnderiumArmor.Leggings>, null]]);
recipes.addShaped(<quantumflux:battlesuit_helmet:1>, [[<quantumflux:upgradeToken>, <quantumflux:battlesuit_helmet>], [<RArm:ItemEnderiumArmor.Helm>, null]]);
recipes.addShaped(<quantumflux:battlesuit_chestplate:1>, [[<quantumflux:upgradeToken>, <quantumflux:battlesuit_chestplate>], [<simplyjetpacks:jetpacksEIO:5>, null]]);
recipes.addShaped(<quantumflux:battlesuit_boots:1>, [[<quantumflux:upgradeToken>, <quantumflux:battlesuit_boots>], [<RArm:ItemEnderiumArmor.Boots>, null]]);
recipes.addShaped(<quantumflux:battlesuit_leggings>, [[<quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>], [<quantumflux:battlesuit_plate>, null, <quantumflux:battlesuit_plate>], [<quantumflux:battlesuit_plate>, null, <quantumflux:battlesuit_plate>]]);
recipes.addShaped(<quantumflux:battlesuit_helmet>, [[<quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>], [<quantumflux:battlesuit_plate>, null, <quantumflux:battlesuit_plate>]]);
recipes.addShaped(<quantumflux:battlesuit_boots>, [[<quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>], [<quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>]]);
recipes.addShaped(<quantumflux:battlesuit_chestplate>, [[<quantumflux:battlesuit_plate>, null, <quantumflux:battlesuit_plate>], [<quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>], [<quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>, <quantumflux:battlesuit_plate>]]);
recipes.addShaped(<quantumflux:battlesuit_plate> * 2, [[<ore:ingotMangalloy>, <quantumflux:energizedCrystal>, <ore:ingotMangalloy>], [<quantumflux:energizedCrystal>, <ore:ingotTitanium>, <quantumflux:energizedCrystal>], [<ore:ingotMangalloy>, <quantumflux:energizedCrystal>, <ore:ingotMangalloy>]]);
recipes.addShaped(<Mekanism:ControlCircuit:3>, [[null, <Mekanism:AtomicAlloy>, null], [<Mekanism:AtomicAlloy>, <Mekanism:ControlCircuit:2>, <Mekanism:AtomicAlloy>], [null, <Mekanism:AtomicAlloy>, null]]);
recipes.addShaped(<Mekanism:ControlCircuit:2>, [[null, <Mekanism:ReinforcedAlloy>, null], [<Mekanism:ReinforcedAlloy>, <Mekanism:ControlCircuit:1>, <Mekanism:ReinforcedAlloy>], [null, <Mekanism:ReinforcedAlloy>, null]]);
recipes.addShaped(<Mekanism:ControlCircuit:1>, [[null, <ore:alloyAdvanced>, null], [<ore:alloyAdvanced>, <Mekanism:ControlCircuit>, <ore:alloyAdvanced>], [null, <ore:alloyAdvanced>, null]]);
recipes.addShaped(<contenttweaker:lapis_plate>, [[<ore:blockLapis>, <ore:blockLapis>, <ore:blockLapis>], [<ore:ingotUnstable>, <ore:ingotUnstable>, <ore:ingotUnstable>], [<ore:blockLapis>, <ore:blockLapis>, <ore:blockLapis>]]);
recipes.addShaped(<ExtraUtilities:extractor_base> * 4, [[null, <ThermalDynamics:ThermalDynamics_32:4>, null], [<EnderIO:blockIngotStorage:3>, <ore:blockEnder>, <EnderIO:blockIngotStorage:3>], [<ore:ingotSteel>, <IronChest:BlockIronChest>, <ore:ingotSteel>]]);
recipes.addShaped(<ExtraUtilities:extractor_base:6> * 4, [[null, <ThermalDynamics:ThermalDynamics_16:6>, null], [<contenttweaker:lapis_plate>, <ore:blockEnder>, <contenttweaker:lapis_plate>], [<ore:ingotSteel>, <ExtraUtilities:drum>, <ore:ingotSteel>]]);
recipes.addShaped(<ExtraUtilities:golden_bag>, [[<ore:blockWoolYellow>, <ore:gemDiamond>, <ore:blockWoolYellow>], [<ore:ingotGold>, <ProjRed|Exploration:projectred.exploration.backpack:4>, <ore:ingotGold>], [<ore:blockWoolYellow>, <minecraft:gold_block>, <ore:blockWoolYellow>]]);
recipes.addShaped(<ExtraUtilities:decorativeBlock1:11>, [[<ExtraUtilities:decorativeBlock1:8>, <ore:pearlEnderEye>, <ExtraUtilities:decorativeBlock1:8>], [<minecraft:ender_eye>, <ExtraUtilities:decorativeBlock1:12>, <ore:pearlEnderEye>], [<ExtraUtilities:decorativeBlock1:8>, <minecraft:ender_eye>, <ExtraUtilities:decorativeBlock1:8>]]);
recipes.addShaped(<ExtraUtilities:endConstructor>, [[<ore:pearlEnderEye>, <Avaritia:Double_Craft>, <ore:pearlEnderEye>], [<ExtraUtilities:decorativeBlock1:1>, <ExtraUtilities:decorativeBlock1:11>, <ExtraUtilities:decorativeBlock1:1>], [<ore:blockEnderObsidian>, <ore:blockSteel>, <ore:blockEnderObsidian>]]);
recipes.addShaped(<ExtraUtilities:endConstructor:2>, [[null, <ore:pearlEnderEye>, null], [<ore:pearlEnderEye>, <ore:blockEnderObsidian>, <ore:pearlEnderEye>], [<ore:blockEnderObsidian>, <ore:blockEnderObsidian>, <ore:blockEnderObsidian>]]);
recipes.addShaped(<ExtraUtilities:decorativeBlock1:1> * 4, [[<ore:materialEnderPearl>, <ore:blockObsidian>, <ore:materialEnderPearl>], [<ore:blockObsidian>, <ore:materialEnderPearl>, <ore:blockObsidian>], [<ore:materialEnderPearl>, <ore:blockObsidian>, <ore:materialEnderPearl>]]);
recipes.addShaped(<ExtraUtilities:angelRing>, [[<minecraft:glass>, <ore:blockUnstable>, <minecraft:glass>], [<Thaumcraft:HoverHarness>, <ForbiddenMagic:StarBlock>, <RArm:ItemCapacitorAmulet:5>.withTag({Energy: 10000000})], [<Botania:flightTiara>, <minecraft:gold_block>, <Mekanism:Jetpack:1>.withTag({stored: {amount: 24000, gasName: "hydrogen"}})]]);
recipes.addShaped(<ExtraUtilities:angelRing:1>, [[<minecraft:feather>, <ore:blockUnstable>, <minecraft:feather>], [<Thaumcraft:HoverHarness>, <ForbiddenMagic:StarBlock>, <RArm:ItemCapacitorAmulet:5>.withTag({Energy: 10000000})], [<Botania:flightTiara>, <minecraft:gold_block>, <Mekanism:Jetpack:1>.withTag({stored: {amount: 24000, gasName: "hydrogen"}})]]);
recipes.addShaped(<ExtraUtilities:angelRing:2>, [[<minecraft:dye:13>, <ore:blockUnstable>, <minecraft:dye:13>], [<Thaumcraft:HoverHarness>, <ForbiddenMagic:StarBlock>, <RArm:ItemCapacitorAmulet:5>.withTag({Energy: 10000000})], [<Botania:flightTiara>, <minecraft:gold_block>, <Mekanism:Jetpack:1>.withTag({stored: {amount: 24000, gasName: "hydrogen"}})]]);
recipes.addShaped(<ExtraUtilities:angelRing:3>, [[<minecraft:leather>, <ore:blockUnstable>, <minecraft:leather>], [<Thaumcraft:HoverHarness>, <ForbiddenMagic:StarBlock>, <RArm:ItemCapacitorAmulet:5>.withTag({Energy: 10000000})], [<Botania:flightTiara>, <minecraft:gold_block>, <Mekanism:Jetpack:1>.withTag({stored: {amount: 24000, gasName: "hydrogen"}})]]);
recipes.addShaped(<ExtraUtilities:angelRing:4>, [[<ore:ingotGold>, <ore:blockUnstable>, <ore:ingotGold>], [<Thaumcraft:HoverHarness>, <ForbiddenMagic:StarBlock>, <RArm:ItemCapacitorAmulet:5>.withTag({Energy: 10000000})], [<Botania:flightTiara>, <minecraft:gold_block>, <Mekanism:Jetpack:1>.withTag({stored: {amount: 24000, gasName: "hydrogen"}})]]);
recipes.addShaped(<BigReactors:BRMetalBlock:4> * 2, [[<ore:blockCyanite>, <ExtraUtilities:block_bedrockium>, <ore:blockCyanite>], [<ore:blockEnderium>, <ore:itemNetherStar>, <ore:blockEnderium>], [<ore:blockCyanite>, <ExtraUtilities:block_bedrockium>, <ore:blockCyanite>]]);
recipes.remove(<ExtraUtilities:block_bedrockium>);
furnace.remove(<ExtraUtilities:block_bedrockium>);
recipes.remove(<ExtraUtilities:bedrockiumIngot>);
mods.avaritia.Compressor.add(<ExtraUtilities:cobblestone_compressed:7>, 43046721, <minecraft:cobblestone>);
mods.tconstruct.Smeltery.removeMelting(<ExtraUtilities:block_bedrockium>);
<ExtraUtilities:block_bedrockium>.addTooltip(format.red(format.bold("Too Heavy!")));
<ExtraUtilities:block_bedrockium>.addTooltip(format.red(format.bold("Can't melt in the smeltery!")));
recipes.addShaped(<ExtraUtilities:block_bedrockium>, [[<ExtraUtilities:cobblestone_compressed:7>, <ExtraUtilities:cobblestone_compressed:6>, <ExtraUtilities:cobblestone_compressed:5>], [<ExtraUtilities:cobblestone_compressed>, <ore:blockVoid>, <ExtraUtilities:cobblestone_compressed:4>], [<ExtraUtilities:cobblestone_compressed:1>, <ExtraUtilities:cobblestone_compressed:2>, <ExtraUtilities:cobblestone_compressed:3>]]);
mods.thermalexpansion.Furnace.removeRecipe(<ExtraUtilities:cobblestone_compressed:7>);
mods.thermalexpansion.Transposer.removeFillRecipe(<minecraft:obsidian>, <liquid:ender>);
mods.tconstruct.Smeltery.removeAlloy(<liquid:enderium.molten>);
mods.tconstruct.Smeltery.removeAlloy(<liquid:signalum.molten>);
mods.tconstruct.Smeltery.removeAlloy(<liquid:lumium.molten>);
mods.thermalexpansion.Transposer.removeFillRecipe(<minecraft:bookshelf>, <liquid:xpjuice>);
mods.thermalexpansion.Transposer.addFillRecipe(40000, <minecraft:bookshelf>, <ExtraUtilities:decorativeBlock1:8>, <liquid:xpjuice> * 10000);
